import path from 'path';
import fs from 'fs';
import type { GitResult } from './git-ops';

const SUGGESTIONS_PATH = path.resolve(__dirname, '../../DESIGN_SUGGESTIONS.md');

interface Suggestion {
  priority: 'high' | 'medium' | 'low';
  title: string;
  description: string;
  file?: string;
}

function formatSuggestionTable(suggestions: Suggestion[], priority: 'high' | 'medium' | 'low'): string {
  const filtered = suggestions.filter((s) => s.priority === priority);
  if (filtered.length === 0) return '_None identified._\n';

  const rows = filtered.map((s) => {
    const file = s.file ? ` (\`${s.file}\`)` : '';
    return `| **${s.title}**${file} | ${s.description} |`;
  });

  return [
    '| Suggestion | Description |',
    '|------------|-------------|',
    ...rows,
    '',
  ].join('\n');
}

export async function updateSuggestions(
  analysis: string,
  suggestions: Suggestion[],
  gitResult: GitResult,
  axeSummary: Record<string, unknown> | null,
  timestamp: string
): Promise<void> {
  const date = timestamp.slice(0, 10);
  const time = timestamp.slice(11, 16).replace(/-/g, ':');
  const displayTs = `${date} ${time} UTC`;

  const gitBlock = gitResult.branch
    ? [
        '**Git:**',
        `- Branch: \`${gitResult.branch}\``,
        `- Commit: \`${gitResult.commitHash ?? 'N/A'}\``,
        `- Files changed: ${gitResult.filesChanged}`,
      ].join('\n')
    : '_No code changes committed (no file changes from agent)._';

  const axeBlock = axeSummary
    ? [
        '**Accessibility (WCAG 2.2 AA):**',
        `- Total violations: ${axeSummary['totalViolations'] ?? '?'}`,
        `- Critical: ${axeSummary['criticalViolations'] ?? '?'} | Serious: ${axeSummary['seriousViolations'] ?? '?'}`,
        `- Moderate: ${axeSummary['moderateViolations'] ?? '?'} | Minor: ${axeSummary['minorViolations'] ?? '?'}`,
      ].join('\n')
    : '_No accessibility report available._';

  const newPassContent = [
    `## Design Review Pass — ${displayTs}`,
    '',
    '### Analysis',
    analysis,
    '',
    '### Metadata',
    gitBlock,
    '',
    axeBlock,
    '',
    '### High Priority',
    formatSuggestionTable(suggestions, 'high'),
    '### Medium Priority',
    formatSuggestionTable(suggestions, 'medium'),
    '### Low Priority',
    formatSuggestionTable(suggestions, 'low'),
    '',
    '---',
    '',
  ].join('\n');

  const HEADER = '# AuctionX Design Suggestions\n\n<!-- Auto-generated by design-review agent. Newest pass first. -->\n\n';

  if (fs.existsSync(SUGGESTIONS_PATH)) {
    const existing = fs.readFileSync(SUGGESTIONS_PATH, 'utf-8');
    // Insert new pass after the file header (first two lines + blank)
    const headerEnd = existing.indexOf('\n\n', existing.indexOf('\n')) + 2;
    const afterHeader = existing.slice(headerEnd);
    fs.writeFileSync(SUGGESTIONS_PATH, HEADER + newPassContent + afterHeader, 'utf-8');
  } else {
    fs.writeFileSync(SUGGESTIONS_PATH, HEADER + newPassContent, 'utf-8');
  }

  console.log(`  [suggestions] Updated: ${SUGGESTIONS_PATH}`);
}
