import { readFileSync } from 'fs';
import { join } from 'path';

/**
 * Loads THE shared NTAG 424 vector file — the same JSON the tag-encoder and
 * tag-hq pytest suites load. Generated by OpenSSL
 * (`test-vectors/generate_ntag424_vectors.py`), never by our own code.
 */

export interface SdmVector {
  name: string;
  sdmMetaReadKey: string;
  sdmFileReadKey: string;
  uid: string;
  counter: number;
  counterLE: string;
  piccDataTag: string;
  piccPadding: string;
  piccPlaintext: string;
  encPiccData: string;
  sv2: string;
  sessionMacKey: string;
  macInput: string;
  fullCmac: string;
  truncatedCmac: string;
}

export interface KdfVector {
  name: string;
  rootKey: string;
  role: 'META' | 'FILE' | 'APP_MASTER';
  version: number;
  uid: string;
  message: string;
  prk: string;
  info: string;
  key: string;
}

export interface ChainVector extends SdmVector {
  rootKey: string;
  version: number;
}

export interface PiccDataTagVector {
  byte: string;
  uidMirrored: boolean;
  ctrMirrored: boolean;
  uidLength: number;
  accept: boolean;
}

export interface SharedVectors {
  _openssl: string;
  sdm: SdmVector[];
  kdf: KdfVector[];
  kdfChain: ChainVector[];
  piccDataTag: PiccDataTagVector[];
}

/** backend/src/__tests__/helpers -> app root */
export const SHARED_VECTOR_PATH = join(__dirname, '..', '..', '..', '..', 'test-vectors', 'ntag424_sdm_vectors.json');

export const loadSharedVectors = (): SharedVectors =>
  JSON.parse(readFileSync(SHARED_VECTOR_PATH, 'utf8')) as SharedVectors;

export const hex = (s: string): Buffer => Buffer.from(s, 'hex');
export const toHex = (b: Buffer): string => b.toString('hex').toUpperCase();

export const testAudit = {
  ctx: { requestId: 'test', actorId: null, actorType: 'system' as const, ip: 'test', route: 'test' },
};
