/**
 * NTAG 424 DNA chip-key derivation spec — S-NFC3.5 (Decisions DB, 2026-10-01).
 *
 * MUST stay byte-identical to `tag-encoder/tag_encoder/keyprovider.py`. Both
 * sides are pinned by `test-vectors/ntag424_sdm_vectors.json` (`kdf` section),
 * generated by OpenSSL — not by either implementation.
 *
 *   msg  = "AM-NTAG424-KDF" || 0x00 || role_ascii || 0x00 || version(1 byte) || uid_bytes
 *          (uid_bytes empty for META; exactly 7 bytes for per-UID roles)
 *   prk  = HMAC-SHA256(root, msg)        — KMS GenerateMac, or local HMAC
 *   key  = HKDF-Expand(prk, info = "NTAG424-DNA/" || role || "/AES128/v" || version, L = 16)
 *
 * Roles the BACKEND may derive (both from the SDM root):
 *   META        fleet-wide SDMMetaReadKey (decrypts PICCData -> UID + counter)
 *   FILE        per-UID SDMFileReadKey (SDM session MAC key derivation)
 *
 * The application master key role lives on a SEPARATE admin root that only
 * the encoder can reach (amended 2026-10-01 by Boss: per-role KMS roots — KMS
 * cannot restrict GenerateMac by message content, so role separation has to be
 * root separation). It is deliberately not representable here: the backend has
 * no code path, type or config that can derive it.
 */

import { createHmac } from 'crypto';

export const TAG_KEY_ROLES = ['META', 'FILE'] as const;
export type TagKeyRole = (typeof TAG_KEY_ROLES)[number];

export const KDF_LABEL = 'AM-NTAG424-KDF';
export const UID_LEN = 7;
export const AES128_KEY_LEN = 16;
export const PRK_LEN = 32;

export interface TagKeyRequest {
  readonly role: TagKeyRole;
  /** Key version, 1..255 — the single version byte in the KDF message. */
  readonly version: number;
  /** 7-byte chip UID. Required for FILE, forbidden for META. */
  readonly uid?: Buffer;
}

export const assertValidRequest = (req: TagKeyRequest): void => {
  // Runtime check, not just the type: a cast or untyped caller must not reach
  // any other role through this module.
  if (!(TAG_KEY_ROLES as readonly string[]).includes(req.role)) {
    throw new Error('Tag key role not permitted in the backend');
  }
  if (!Number.isInteger(req.version) || req.version < 1 || req.version > 255) {
    throw new Error('Tag key version must be an integer in 1..255');
  }
  if (req.role === 'META') {
    if (req.uid !== undefined && req.uid.length !== 0) {
      throw new Error('META keys are fleet-wide and take no UID');
    }
  } else if (!req.uid || req.uid.length !== UID_LEN) {
    throw new Error(`${req.role} keys require a ${UID_LEN}-byte UID`);
  }
};

/** The HMAC message for one derivation. Public, non-secret. */
export const kdfMessage = (req: TagKeyRequest): Buffer => {
  assertValidRequest(req);
  return Buffer.concat([
    Buffer.from(KDF_LABEL, 'ascii'),
    Buffer.from([0x00]),
    Buffer.from(req.role, 'ascii'),
    Buffer.from([0x00]),
    Buffer.from([req.version]),
    req.role === 'META' ? Buffer.alloc(0) : (req.uid as Buffer),
  ]);
};

/** The HKDF info label. Public, non-secret. */
export const kdfInfo = (role: TagKeyRole, version: number): Buffer =>
  Buffer.from(`NTAG424-DNA/${role}/AES128/v${version}`, 'ascii');

/** RFC 5869 HKDF-Expand with HMAC-SHA256. */
export const hkdfExpand = (prk: Buffer, info: Buffer, length: number): Buffer => {
  if (prk.length < PRK_LEN) throw new Error('HKDF PRK must be at least 32 bytes');
  if (length > 255 * 32) throw new Error('HKDF length too large');
  const blocks: Buffer[] = [];
  let previous = Buffer.alloc(0);
  let produced = 0;
  for (let counter = 1; produced < length; counter++) {
    previous = createHmac('sha256', prk)
      .update(Buffer.concat([previous, info, Buffer.from([counter])]))
      .digest();
    blocks.push(previous);
    produced += previous.length;
  }
  return Buffer.concat(blocks).subarray(0, length);
};

/** prk -> 16-byte AES-128 key for this role/version. */
export const expandToAesKey = (prk: Buffer, req: TagKeyRequest): Buffer =>
  hkdfExpand(prk, kdfInfo(req.role, req.version), AES128_KEY_LEN);
