/**
 * CascadeOrchestrator — Payment processor waterfall with risk-based routing.
 *
 * Routes payments through a risk-tiered cascade of processors. Risk level is
 * determined by the content flags on the listing, evaluated server-side in
 * process-payment/index.ts before reaching this orchestrator.
 *
 * NOWPayments (crypto) is intentionally excluded from all cascades — it is
 * a separate user-opt-in path handled in process-payment/index.ts directly.
 *
 * @module CascadeOrchestrator
 */
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { ProcessorFactory } from './ProcessorFactory.ts';
import {
  ProcessorType,
  PaymentRequest,
  PaymentResponse,
  PaymentStatus,
  RiskAssessment,
  ProcessorConfig,
} from './types.ts';
import { logger } from '../utils/logger.ts';

export class CascadeOrchestrator {
  private config: ProcessorConfig;

  /**
   * Processor cascade order by risk level.
   * NOWPayments is NEVER included — crypto payments are user opt-in only.
   * Business rules: LOW → Stripe first; MEDIUM → skip Stripe; HIGH → Signature/CCBill only.
   */
  private readonly processorCascade: Record<string, ProcessorType[]> = {
    LOW:    ['STRIPE', 'PAYMENTCLOUD', 'SIGNATURE', 'CCBILL'],
    MEDIUM: ['PAYMENTCLOUD', 'SIGNATURE', 'CCBILL'],
    HIGH:   ['SIGNATURE', 'CCBILL'],
  };

  /**
   * Risk scores for each DB-valid content_flag enum value.
   * Uses highest individual score (not additive sum) to determine risk level.
   * Thresholds: score >= 6 → HIGH, score >= 3 → MEDIUM, else LOW.
   *
   * SWIMWEAR, LINGERIE, PERSONAL_ITEM, FETISH added to DB enum via
   * migration 20260303000002_content_flag_enum_expansion.sql.
   */
  private readonly FLAG_SCORES: Record<string, number> = {
    // LOW risk (score 1–2)
    CONCERT_GEAR:        1,
    MEMORABILIA:         1,
    AUTOGRAPHED:         1,
    SPORTS_EQUIPMENT:    1,
    VINTAGE_COLLECTIBLES:1,
    FAN_MERCHANDISE:     1,
    CREATOR_MERCH:       1,
    GAMING:              1,
    COLLECTIBLES:        1,
    DIGITAL_GOODS:       1,
    COSPLAY:             2,
    // MEDIUM risk (score 3–5)
    SWIMWEAR:            3,
    LINGERIE:            4,
    PERSONAL_ITEM:       4,
    FETISH:              5,
    // HIGH risk (score 6+)
    INTIMATE_ITEMS:      6,
    NSFW:                7,
    '18_PLUS':           7,
    ADULT_CONTENT:       8,
    EXPLICIT:            10,
  };

  constructor(config: ProcessorConfig) {
    this.config = config;
  }

  /**
   * Process a payment through the cascade. Tries processors in risk-appropriate
   * order, skipping unavailable ones (missing credentials). Logs each attempt
   * to payment_attempts if a transactionId is provided in request metadata.
   *
   * @param request - PaymentRequest with metadata.transactionId pre-set by caller
   * @returns PaymentResponse with selectedProcessor and riskAssessment in processorResponse
   */
  async processPayment(request: PaymentRequest): Promise<PaymentResponse> {
    // transactionId pre-generated by process-payment/index.ts for attempt logging
    const transactionId = request.metadata.transactionId as string | undefined;
    const supabase = createClient(this.config.supabaseUrl, this.config.supabaseKey);

    try {
      const riskAssessment = this.assessRisk(request.metadata);

      logger.info('CascadeOrchestrator: Risk assessment complete', {
        level: riskAssessment.level,
        flags: riskAssessment.flags,
        score: riskAssessment.score,
      });

      const processorOrder = this.processorCascade[riskAssessment.level];
      let attemptNumber = 0;

      for (const processorType of processorOrder) {
        if (!ProcessorFactory.isProcessorAvailable(processorType)) {
          logger.warn(`CascadeOrchestrator: Processor ${processorType} not available, skipping`);
          continue;
        }

        attemptNumber++;
        const startTime = Date.now();

        logger.info(`CascadeOrchestrator: Attempting processor ${processorType}`, { attemptNumber });

        try {
          const processor = ProcessorFactory.createProcessor(processorType, this.config);

          const result = await processor.processPayment(
            request.amount,
            request.currency,
            request.paymentMethod,
            request.metadata
          );

          const responseTimeMs = Date.now() - startTime;

          // Log each attempt to payment_attempts for audit trail
          if (transactionId) {
            await supabase.from('payment_attempts').insert({
              transaction_id: transactionId,
              processor: processorType,
              attempt_number: attemptNumber,
              success: result.success,
              processor_payment_id: (result as any).transactionId ?? null,
              error_code: (result as any).errorCode ?? null,
              error_message: (result as any).errorMessage ?? null,
              response_time_ms: responseTimeMs,
              raw_response: result,
            });
          }

          if (result.success) {
            logger.info(`CascadeOrchestrator: Payment successful with ${processorType}`, {
              processorPaymentId: (result as any).transactionId,
            });

            return {
              success: true,
              transactionId: (result as any).transactionId,
              status: PaymentStatus.COMPLETED,
              amount: result.amount ?? request.amount,
              currency: result.currency ?? request.currency,
              processorResponse: {
                selectedProcessor: processorType,
                riskAssessment,
              },
            };
          }

          // PENDING = processor requires async confirmation (e.g., CCBill hosted form)
          if ((result as any).status === PaymentStatus.PENDING) {
            logger.info(`CascadeOrchestrator: Payment pending with ${processorType}`);
            return {
              success: false,
              status: PaymentStatus.PENDING,
              amount: request.amount,
              currency: request.currency,
              processorResponse: {
                selectedProcessor: processorType,
                riskAssessment,
                pendingDetails: result,
              },
            };
          }

          // FAILED = processor declined, try next in cascade
          logger.warn(`CascadeOrchestrator: Processor ${processorType} declined payment, trying next`);

        } catch (processorError) {
          const responseTimeMs = Date.now() - startTime;

          logger.error(`CascadeOrchestrator: Processor ${processorType} threw error`, {
            error: processorError,
          });

          // Log the error attempt
          if (transactionId) {
            await supabase.from('payment_attempts').insert({
              transaction_id: transactionId,
              processor: processorType,
              attempt_number: attemptNumber,
              success: false,
              error_message: processorError instanceof Error ? processorError.message : 'Processor error',
              response_time_ms: responseTimeMs,
              raw_response: { error: String(processorError) },
            });
          }
          // Continue to next processor
        }
      }

      // All configured processors failed
      logger.error('CascadeOrchestrator: All processors failed or unavailable');

      return {
        success: false,
        error: 'Payment could not be processed. Please try a different payment method.',
        status: PaymentStatus.FAILED,
        amount: request.amount,
        currency: request.currency,
      };

    } catch (error) {
      logger.error('CascadeOrchestrator: Orchestration error', { error });

      return {
        success: false,
        error: error instanceof Error ? error.message : 'Payment processing failed',
        status: PaymentStatus.FAILED,
        amount: request.amount,
        currency: request.currency,
      };
    }
  }

  /**
   * Assess risk level from content flags. Uses the HIGHEST individual flag score,
   * not the sum, per business rules (adding more low-risk flags shouldn't escalate risk).
   * Only recognized DB-valid flags are scored; unknown flags are ignored.
   */
  private assessRisk(metadata: Record<string, unknown>): RiskAssessment {
    const contentFlags = (metadata.contentFlags as string[]) || [];
    const recognizedFlags = contentFlags.filter(f => f in this.FLAG_SCORES);

    // Use max score (not additive) — SWIMWEAR + LINGERIE stays MEDIUM, not HIGH
    const maxScore = recognizedFlags.length > 0
      ? Math.max(...recognizedFlags.map(f => this.FLAG_SCORES[f]))
      : 0;

    let level: 'LOW' | 'MEDIUM' | 'HIGH';
    if (maxScore >= 6) level = 'HIGH';
    else if (maxScore >= 3) level = 'MEDIUM';
    else level = 'LOW';

    return { level, flags: recognizedFlags, score: maxScore };
  }

  /**
   * Returns the first available processor for a given risk level.
   * Used for informational/health-check purposes.
   */
  getRecommendedProcessor(riskLevel: 'LOW' | 'MEDIUM' | 'HIGH'): ProcessorType | null {
    const processors = this.processorCascade[riskLevel];

    for (const processorType of processors) {
      if (ProcessorFactory.isProcessorAvailable(processorType)) {
        return processorType;
      }
    }

    return null;
  }

  /** Returns all processors with credentials configured in the environment. */
  getAvailableProcessors(): ProcessorType[] {
    const allProcessors: ProcessorType[] = ['STRIPE', 'PAYMENTCLOUD', 'SIGNATURE', 'CCBILL', 'NOWPAYMENTS'];
    return allProcessors.filter(type => ProcessorFactory.isProcessorAvailable(type));
  }
}
