"""S-NFC3.5 — AN12196 SDM + KDF against the SHARED OpenSSL vector file.

test-vectors/ntag424_sdm_vectors.json is loaded here, by backend vitest and by
tag-hq pytest. It was generated by OpenSSL (test-vectors/generate_ntag424_vectors.py),
not by this code, so agreement here is agreement with an independent oracle.
"""

import json
from pathlib import Path

import pytest

from tag_encoder.keyprovider import LocalKeyProvider, kdf_info, kdf_message
from tag_encoder.ntag424.encode import (
    build_picc_plaintext,
    build_sv2,
    decrypt_picc_block,
    decrypt_picc_data,
    encode_sun,
    encrypt_picc_block,
    extract_mac_input,
    full_sdm_mac,
    parse_picc_data_tag,
    parse_picc_plaintext,
    sdm_mac,
    session_mac_key,
    truncate_sdm_mac,
    v2_mac_input,
    verify_sdm_mac,
    verify_sun,
)

VECTORS = json.loads(
    (Path(__file__).resolve().parents[2] / "test-vectors" / "ntag424_sdm_vectors.json").read_text()
)
SDM = VECTORS["sdm"]
GOLDEN = next(v for v in SDM if v["name"] == "an12196_golden_zero_keys")
H = bytes.fromhex


def test_shared_file_is_the_openssl_one():
    assert "OpenSSL" in VECTORS["_openssl"]
    assert len(SDM) >= 5 and len(VECTORS["kdf"]) >= 12


# --- AN12196 golden vector #1, every intermediate -------------------------------

def test_golden_picc_plaintext():
    assert decrypt_picc_block(GOLDEN["encPiccData"], bytes(16)).hex().upper() == "C704DE5F1EACC0403D0000DA5CF60941"


def test_golden_uid_and_counter():
    picc = decrypt_picc_data(GOLDEN["encPiccData"], bytes(16))
    assert picc.uid_hex == "04DE5F1EACC040"
    assert picc.counter_le.hex().upper() == "3D0000"
    assert picc.counter == 61


def test_golden_sv2_session_key_cmac_truncation():
    uid, ctr = H("04DE5F1EACC040"), H("3D0000")
    assert build_sv2(uid, ctr).hex().upper() == "3CC30001008004DE5F1EACC0403D0000"
    assert session_mac_key(bytes(16), uid, ctr).hex().upper() == "3FB5F6E3A807A03D5E3570ACE393776F"
    assert full_sdm_mac(bytes(16), uid, ctr, b"").hex().upper() == "E194C7EE12D9F7EE8A65C8331B704386"
    assert truncate_sdm_mac(H("E194C7EE12D9F7EE8A65C8331B704386")).hex().upper() == "94EED9EE65337086"
    assert sdm_mac(bytes(16), uid, ctr, b"").hex().upper() == "94EED9EE65337086"


# --- every shared SDM vector ---------------------------------------------------

@pytest.mark.parametrize("v", SDM, ids=[v["name"] for v in SDM])
def test_decrypt_side_every_intermediate(v):
    meta, file_key = H(v["sdmMetaReadKey"]), H(v["sdmFileReadKey"])
    assert decrypt_picc_block(v["encPiccData"], meta).hex().upper() == v["piccPlaintext"]
    picc = decrypt_picc_data(v["encPiccData"], meta)
    assert (picc.uid_hex, picc.counter, picc.counter_le.hex().upper()) == (v["uid"], v["counter"], v["counterLE"])
    uid, ctr, mi = H(v["uid"]), H(v["counterLE"]), H(v["macInput"])
    assert build_sv2(uid, ctr).hex().upper() == v["sv2"]
    assert session_mac_key(file_key, uid, ctr).hex().upper() == v["sessionMacKey"]
    assert full_sdm_mac(file_key, uid, ctr, mi).hex().upper() == v["fullCmac"]
    assert sdm_mac(file_key, uid, ctr, mi).hex().upper() == v["truncatedCmac"]
    assert verify_sdm_mac(file_key, uid, ctr, mi, H(v["truncatedCmac"]))


@pytest.mark.parametrize("v", SDM, ids=[v["name"] for v in SDM])
def test_encode_side(v):
    plain = build_picc_plaintext(v["uid"], v["counter"], v["piccPadding"])
    assert plain.hex().upper() == v["piccPlaintext"]
    assert encrypt_picc_block(plain, H(v["sdmMetaReadKey"])).hex().upper() == v["encPiccData"]
    if v["macInput"] == "":
        r = encode_sun(v["uid"], v["counter"], v["sdmMetaReadKey"], v["sdmFileReadKey"],
                       "https://am.example", "tok", v["piccPadding"])
        assert (r.enc_picc_hex, r.cmac_hex) == (v["encPiccData"], v["truncatedCmac"])


@pytest.mark.parametrize("v", SDM, ids=[v["name"] for v in SDM])
def test_every_flipped_mac_byte_fails(v):
    file_key, uid, ctr, mi = H(v["sdmFileReadKey"]), H(v["uid"]), H(v["counterLE"]), H(v["macInput"])
    for i in range(8):
        bad = bytearray(H(v["truncatedCmac"]))
        bad[i] ^= 0x01
        assert not verify_sdm_mac(file_key, uid, ctr, mi, bytes(bad))


def test_nonempty_mac_input_range_is_bound():
    v = next(x for x in SDM if x["macInput"])
    args = (H(v["sdmFileReadKey"]), H(v["uid"]), H(v["counterLE"]))
    assert verify_sdm_mac(*args, H(v["macInput"]), H(v["truncatedCmac"]))
    assert not verify_sdm_mac(*args, b"", H(v["truncatedCmac"]))
    blob = b"PREFIX" + H(v["macInput"]) + b"SUFFIX"
    assert extract_mac_input(blob, 6, 6 + len(H(v["macInput"]))) == H(v["macInput"])
    with pytest.raises(ValueError):
        extract_mac_input(blob, 5, 4)


@pytest.mark.parametrize("t", VECTORS["piccDataTag"], ids=[t["byte"] for t in VECTORS["piccDataTag"]])
def test_picc_data_tag(t):
    tag = parse_picc_data_tag(int(t["byte"], 16))
    assert (tag.uid_mirrored, tag.ctr_mirrored, tag.uid_length) == (t["uidMirrored"], t["ctrMirrored"], t["uidLength"])
    assert tag.acceptable is t["accept"]
    plain = bytearray(H(GOLDEN["piccPlaintext"]))
    plain[0] = int(t["byte"], 16)
    assert (parse_picc_plaintext(bytes(plain)) is not None) is t["accept"]


# --- KDF -------------------------------------------------------------------------

OTHER_ROOT = bytes.fromhex("77" * 32)


def _provider_for(v):
    root = H(v["rootKey"])
    if v["role"] in ("APP_MASTER", "APP_KEY1", "APP_KEY4"):
        return LocalKeyProvider(OTHER_ROOT, root, allow_local_keys=True)
    return LocalKeyProvider(root, OTHER_ROOT, allow_local_keys=True)


@pytest.mark.parametrize("v", VECTORS["kdf"], ids=[v["name"] for v in VECTORS["kdf"]])
def test_kdf_vectors(v):
    uid = H(v["uid"]) if v["uid"] else None
    serial = H(v["serial"]) if v["serial"] else None
    assert kdf_message(v["role"], v["version"], uid, serial).hex().upper() == v["message"]
    assert kdf_info(v["role"], v["version"]).hex().upper() == v["info"]
    assert _provider_for(v).derive_key(v["role"], v["version"], uid, serial).hex().upper() == v["key"]


@pytest.mark.parametrize("v", VECTORS["kdfChain"], ids=[v["name"] for v in VECTORS["kdfChain"]])
def test_kdf_chain_into_sdm(v):
    p = LocalKeyProvider(H(v["rootKey"]), OTHER_ROOT, allow_local_keys=True)
    meta = p.derive_key("META", v["version"])
    serial = H(v["serial"]) if v["serial"] else None
    file_key = p.derive_key("FILE", v["version"], H(v["uid"]), serial)
    assert (meta.hex().upper(), file_key.hex().upper()) == (v["sdmMetaReadKey"], v["sdmFileReadKey"])
    r = encode_sun(v["uid"], v["counter"], meta, file_key, "https://am.example", "tok", v["piccPadding"], serial)
    assert (r.enc_picc_hex, r.cmac_hex) == (v["encPiccData"], v["truncatedCmac"])
    if serial is not None:
        assert v2_mac_input(serial, r.enc_picc_hex).hex().upper() == v["macInput"]
        assert f"?sn={v['serial']}&picc_data={r.enc_picc_hex}&cmac={r.cmac_hex}" in r.sun_url
        res = verify_sun(r.enc_picc_hex, r.cmac_hex, meta, lambda _u: file_key, 4, v["uid"], serial)
        assert res.valid
        # the same tap under the twin chip's serial (same UID) must not verify
        twin = next(c for c in VECTORS["kdfChain"] if c["uid"] == v["uid"] and c["serial"] not in ("", v["serial"]))
        twin_file = p.derive_key("FILE", v["version"], H(v["uid"]), H(twin["serial"]))
        assert twin_file != file_key
        assert not verify_sun(r.enc_picc_hex, r.cmac_hex, meta, lambda _u: twin_file, 4, v["uid"], H(twin["serial"])).valid


# --- verify pipeline (mirror of backend validateSunScan) ---------------------

CHAIN_A, CHAIN_B = VECTORS["kdfChain"][0], VECTORS["kdfChain"][1]
PROV = LocalKeyProvider(H(CHAIN_A["rootKey"]), OTHER_ROOT, allow_local_keys=True)
META = PROV.derive_key("META", 1)


def _file(uid):
    return PROV.derive_key("FILE", 1, uid)


def _tap(v, counter=5):
    return encode_sun(v["uid"], counter, META, _file(H(v["uid"])), "https://am.example", "tok", "0102030405")


def test_verify_accepts_fresh_tap():
    r = _tap(CHAIN_A)
    res = verify_sun(r.enc_picc_hex, r.cmac_hex, META, _file, 4, CHAIN_A["uid"])
    assert res.valid and res.counter == 5 and res.error is None


def test_verify_replay_detected():
    r = _tap(CHAIN_A)
    assert verify_sun(r.enc_picc_hex, r.cmac_hex, META, _file, 5, CHAIN_A["uid"]).error == "replay_detected"


def test_verify_flipped_mac_is_invalid_signature():
    r = _tap(CHAIN_A)
    bad = bytearray(H(r.cmac_hex))
    bad[7] ^= 0x10
    assert verify_sun(r.enc_picc_hex, bad.hex(), META, _file, 0, CHAIN_A["uid"]).error == "invalid_signature"


def test_verify_tag_a_url_with_tag_b_uid_fails():
    r = _tap(CHAIN_A)
    assert verify_sun(r.enc_picc_hex, r.cmac_hex, META, _file, 0, CHAIN_B["uid"]).error == "uid_mismatch"


def test_verify_spliced_mac_fails():
    a, b = _tap(CHAIN_A), _tap(CHAIN_B)
    assert verify_sun(a.enc_picc_hex, b.cmac_hex, META, _file, 0).error == "invalid_signature"


def test_verify_malformed():
    assert verify_sun("00", "11", META, _file, 0).error == "malformed"
    assert verify_sun("ZZ" * 16, "11" * 8, META, _file, 0).error == "malformed"
